### ISSUE TITLE
Looping bug in interpreter

### ISSUE THREAD

**Issue by rdebath** [Glubs9/python-interpreter-for-brainfuck-using-numbers#1]
This little BF program should print `79 75 10` or `OK` in ASCII
```bf
++++++++++[>++++++++>+<<-]>-.<----[>->>[[]<<++>>][+]<<<+]>.>.
```
It hangs after the first output.
```
$ bfi -fintio ok-test3.b
79
75
10
$ time python brainfuck.py ok-test3.b
79
^CTraceback (most recent call last):
  File "brainfuck.py", line 68, in <module>
    main() #I have it all in a main function just because it looks nicer and I can re-use useful keywords like tokens.
  File "brainfuck.py", line 66, in main
    interp(tokens)
  File "brainfuck.py", line 37, in interp
    elif tokens[n] == ",":
KeyboardInterrupt
Command exited with non-zero status 1
12.36user 0.00system 0:12.37elapsed 99%CPU (0avgtext+0avgdata 5608maxresident)k
0inputs+0outputs (0major+566minor)pagefaults 0swaps
$
```

**Comment by Glubs9** [comment]
I was looking at your program and I was a bit confused about a large portion of it, it seemed to be completely unnecessary to me so I deleted it, (the part I'm talking about is the [[]<<++>>][+] part), after deleting this I got ++++++++++[>++++++++>+<<-]>-.<----[>-<+]>.>. which does work with my interpreter. Though the original should work. this is probably a problem with the way my interpreter is skipping the brackets. I will fix this and get back to you.

**Comment by Glubs9** [comment]
lol sorry did not mean to close the issue

**Comment by Glubs9** [comment]
the issue was that when I was skipping past the empty brackets I went one token further than I should've, So in the interp function I added n -= 1 at the bottom of the if statement for "[" tokens which made it work!, Thank you so much for the feedback it really helped!

**Comment by rdebath** [comment]
> ... seemed to be completely unnecessary ...

You're not wrong, from the "printing OK" point of view, the extra code is for testing interpreters.
Still, this sounds like a very good reason to stick with my "Hello World" program instead, it has much less obviously "unnecessary" code.

``` bf
+[>[<-[]>+[>+++>[+++++++++++>][>]-[<]>-]]++++++++++<]>
>>>>>----.<<+++.<-..+++.<-.>>>.<<.+++.------.>-.<<+.<.
```

**Comment by Glubs9** [comment]
Thanks for the test!
